### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#145]
@jobovy brought up the issue that some people might favour a non-GPL license for REBOUND.

A non-GPL license would, for example, allow people to include the integrators in REBOUND in other open source projects that are not under a GPL license (astropy, etc). This seems like a desirable thing to do, I think.

The only problem I have is that I would like to avoid companies using our software for commercial purposes without contributing to the open source community. As an example, I'm thinking of http://www.spaceroutes.com, a company optimizing spacecraft trajectories. They have [14 patents](https://www.google.com/search?tbo=p&tbm=pts&hl=en&q=ininventor:%22Edward+A.+Belbruno%22&gws_rd=ssl) on this topic which I find ethically problematic, to say the least. 

I'll leave this issue open for a while. Please post your comments.

**Comment by jobovy** [comment]
I understand the concern about commercial applications. IANAL, but as far as I can tell, there is no open-source license that directly restricts commercial use (GPL allows commercial use, but you have to provide the source and allow it to be shared, which automatically kind of restricts commercial use!). So I don't think that there is a simple solution that would allow BSD/MIT-licensed software packages (like astropy) to use REBOUND, while not allowing commercial applications (such a license would not be considered open source).

**Comment by techdragon** [comment]
@hannorein Even a switch from GPL to LGPL might be an improvement. Being able to treat the library as a library and respect its LGPL license separately, not requiring users to switch the rest of their project to the GPL would be a welcome improvement.

**Comment by hannorein** [comment]
@techdragon What do you intend to use REBOUND for?

**Comment by techdragon** [comment]
Currently the only use I have for Rebound is in games. Rebound is currently the front runner on a very short list of ways I can work out the proper N Body physics involved in a few game ideas I'm thinking about, and since a few of the ideas would actually use realistic N Body physics as part of the overall game design, I was motivated to find out how to do the physics _right_. 

While I can happily use Rebound for my personal prototyping, if I ever want to release one of these games the fact that the GPL, and GPLv3 in particular, is at odds with the current dominant application distribution platforms, such as App Store, Steam, XBox, etc, prevents me doing so. There are terms of service issues about granting of rights that the GPL requires that the terms of service explicitly reserve, and with the GPLv3 and possibly even the LGPLv3 (its not 100% clear in the LGPLv3 case) there are issues with code signing of application bundles and v3.

**Comment by hannorein** [comment]
Thanks for the explanation. I don't see this use case as a good reason to change the license. However, you can always ask for permission to use REBOUND in such a project!
