### ISSUE TITLE
Logarithmic potential causes issues for additional_forces?

### ISSUE THREAD

**Issue by guillochon** [hannorein/rebound#194]
Hi, a student is attempting to use Rebound to integrate particle trajectories in a galaxy potential, with additional forces from a point mass. One of the terms in the potential contains a logarithm (the halo term), and this term seems to cause all the integrators in Rebound we tried to choke, with the integrator choosing a timestep that is several orders of magnitude smaller than when those log terms are absent. Commenting out this one term and things work fine, we've also verified that the force magnitude of the term looks OK as compared to the other terms.

We have an example ipython notebook showing this behavior available here: https://www.dropbox.com/s/5kjrh47jn6gnzek/Unbound%20debris-broken.ipynb?dl=1, the notebook as is should hang when it attempts to integrate as the time-step is much smaller than the total integration time. Commenting out the halo terms (the last terms in the galAccel function, preceded by a `mha` coefficient) allows the integration to finish; so does replacing the log term (`logterm`) with its Taylor series.

Is this simply a limitation of the available integrators in Rebound?

**Comment by hannorein** [comment]
Are you sure this potential is well behaved? Doesn't the term 

     mha*ps[1].x*((logterm/r**3)-(1.0/rterm))

diverge as `r->0`.

**Comment by hannorein** [comment]
I also seems that the particles are on nearly radial orbits, so this term would indeed blowup.

But if I'm missing something, let me know. Maybe you can simplify the example a little so that it's easier for me to see what's going on. E.g. remove all the loops and just run one simulation that shows the behaviour.

**Comment by guillochon** [comment]
Indeed the particles are on nearly radial orbits, but they should never return to exactly r = 0, and the issue seems to start at t = 0 from the initial conditions, which places the particle at its periapse. If you uncomment the `logterm` alternative definition (`logterm = r/rh`, the first term in the Taylor expansion), the integrator seems to work. There's just something about including a `log` in the the potential that is causing issues.

I made the example a little simpler if that helps.

**Comment by hannorein** [comment]
Ok. I think I found the issue. You are running into a floating point problem. The red line show the force from the log term:

![screen shot 2016-06-21 at 5 09 18 pm](https://cloud.githubusercontent.com/assets/53376/16246364/ea2758b2-37d2-11e6-9ab2-2235c32417fa.png)

Note that it is the dominant contribution to the force. The integrator tries really hard to integrate this force accurately which will of course not work because it's complete gibberish. You need to make sure you don't subtract two almost equal numbers in your calculation. Here, the problem comes from those two terms:

    mha*ps[1].x*(logterm/r**3)
    -mha*ps[1].x*(1.0/rterm)

I hope this helps.

**Comment by guillochon** [comment]
Thanks @hannorein! Forwarding to the student, should be helpful.
