### ISSUE TITLE
Rebound won't show the entire eccentric orbits with OPENGL on

### ISSUE THREAD

**Issue by meldonization** [hannorein/rebound#212]
![eccentric orbit](https://cloud.githubusercontent.com/assets/1425792/16857500/00ec36d0-49d5-11e6-9f25-2782482b7964.png)

**Comment by meldonization** [comment]
I think t's better for the display routine to calculate the entire elliptical orbit before draw the whole sphere.

**Comment by hannorein** [comment]
Can you elaborate "won't show the entire eccentric orbit"? In the picture, the orbit might be a bit rough around the edges because it's highly eccentric, but otherwise it looks ok.

**Comment by dtamayo** [comment]
I think he/she means that you don't see the apocenter.  I think it's hard to pick a default that works for everyone.  People studying comets when they come by pericenter would want to see something like this zoomed in rather than be out at thousands of AU.  There are also cases where calculating the apocenter using osculating elements could give you very wrong results.  I would lean toward leaving the default based on the orbital distances, particularly since the user can always set the visualization size with reb_configure_box...

**Comment by hannorein** [comment]
I still don't understand. You can zoom in and out during the simulation...

**Comment by dtamayo** [comment]
Also true!

**Comment by dtamayo** [comment]
Sec 2.5 here http://rebound.readthedocs.io/en/latest/c_quickstart.html for anyone finding this thread later.
