### ISSUE TITLE
Memory leak when using multiple simulation instances from Python

### ISSUE THREAD

**Issue by jbedorf** [hannorein/rebound#238]
I ran into an issue of increased memory usage when creating 'simulation' instances in a loop like this:

```
for simi in fsim:
  gravity_code = rebound.Simulation.from_file(simi)
  #do stuff
  del gravity_code
```

The delete does not free up the simulation structure, nor the particles bound to the simulation since the 
_reb_free_simulation_  function is never called from Python.

I verified this by manually adding a cleanup function which executes:
`clibrebound.reb_free_simulation(byref(self))`

This frees up the registered memory.

**Comment by hannorein** [comment]
Thanks. I'll look into it.

**Comment by dtamayo** [comment]
I think this is more of a python issue... del a does not call a.__del__, it only decreases a's reference count. Only when there are no more references is a.__del__ called (which in the case of the Simulation class calls reb_free_simulation). I think the problem is that python keeps extra references floating around that we don't explicitly create. Something as simple and ugly as calling del several times would probably work.

**Comment by dtamayo** [comment]
I just checked that a simple case:

```
import rebound

sim = rebound.Simulation()
sim.add(m=1.)
sim.save("test.bin")

sim = rebound.Simulation.from_file("test.bin")
```

calls sim.\_\_del\_\_. You can check whether your code has created more references to gravity_code in #do stuff with

```
from sys import getrefcount as grc
print(grc(gravity_code))
```

This will always output the number of rerences to gravity_code + 1 (because it internally creates a reference). If this prints 2, and you call del gravity_code, it will call gravity_code.\_\_del\_\_, and the memory not being freed is a rebound problem. If it's 3 or higher, I don't think we can do anything on the rebound side. You should probably simply call

```
gravity_code.__del__()
```

**Comment by jbedorf** [comment]
Interesting, it reports 3 in my script right after loading:
```
for simi in fsim:
  gravity_code = rebound.Simulation.from_file(simi)
  print("Refs: ", grc(gravity_code))
```
Prints: Refs: 3 

But in your simple example script it reports 2. I will dig a bit deeper

**Comment by jbedorf** [comment]
Oke the '3' came from the memory usage tracker I was using.

Testing some more it turns out that if you create a Simulation instance with:
`sim = rebound.Simulation()`
It will pass this if statement:
` if self._b_needsfree_ == 1: # `

But if you create it using:
`sim = rebound.Simulation.from_file("test.bin")
`
Then the value of _b_needsfree is: 0  and hence the c-library is not called.

**Comment by hannorein** [comment]
Thanks for digging so deep! I think the solution is to not call `clibrebound.reb_create_simulation()` within `Simulation.from_file()` but instead allocate the memory with ctypes, then call `clibrebound.reb_init_simulation()` and finally `clibrebound.reb_create_simulation_from_binary_with_messages()`. The same should probably be done for the `Simjulation.from_archive()` function. 

I hope we're not missing an important point.
