### ISSUE TITLE
testparticle_type and whfast

### ISSUE THREAD

**Issue by silburt** [hannorein/rebound#253]
It looks like any integrator using the kepler_solver doesn't do the right thing when the planets have mass but are initialized as either test bodies or semi-active bodies. Attached is a simple notebook that reproduces this result.

The IAS15 and leapfrog integrators will do the correct thing. 
[IAS_WHFAST_difference.ipynb.zip](https://github.com/hannorein/rebound/files/842404/IAS_WHFAST_difference.ipynb.zip)

**Comment by hannorein** [comment]
I can confirm that this is indeed an issue. It's confusing and potentially hard to fix because it depends on the coordinate system used. A fix for `democraticheliocentric` coordinates is on the `testparticlewhfast` branch. There are probably other issues. I'll try to come up with a set of unit tests first...

A short snippet to reproduce the issue:

```
sim = rebound.Simulation()
sim.N_active = 1
sim.integrator = "whfast"
sim.ri_whfast.coordinates = "democraticheliocentric"
sim.testparticle_type = 0
sim.add(m=1)
sim.add(x=1, vy=1, m=0.5)
```

**Comment by hannorein** [comment]
This is still an issue. In particular for `jacobi` where it seems it can't handle test particles at all. I've added a few new test (currently failing) on the `whfasttestparticle` branch.

**Comment by hannorein** [comment]
The e266142 commit should not only fix this, but also improve stability/accuracy for simulations with a large number of testparticles. I'm not merging it just yet because I'm still a bit unsure about the implications for long term accuracy.

Note that using testparticles and JACOBI coordinates together is probably rarely a good idea (because test particles are always added last).
