### ISSUE TITLE
Output resolution in ipython_examples/Churyumov-Gerasimenko.ipynb

### ISSUE THREAD

**Issue by ridlo** [hannorein/rebound#290]
Time resolution of the output in the example is ~25.5 days, but this note is talking about the date of encounter.  I think it is a bit weird. :) 
Maybe we can increase a bit the Noutputs and talk about this 'output resolution' in the notebook? related to the problem of computing "exact close encounter time".

I want to ask because I am not sure about this, 
if we are doing solar system simulation and want to convert "simulation time" to the "real time", the correct number for year variable in this notebook should be  sqrt(4*pi^2/ (1+3.00348961e-06)) because the mass of the earth = 3.00348961e-06 Msun
and the last line should be 
`encounterdate = datetime.datetime.today() + datetime.timedelta(days=365.256363004*closeencountertime)`
?

Thank you.

**Comment by hannorein** [comment]
Yes, the date is not very accurate because of the output interval. Increasing the output cadence is one way to fix this. Or, check for close encounters using one of the collision detection modules while the simulation is running (this would be better).

It seems unlikely that you ever want to know a collision time more accurately than ~1e-6. So I would not worry about this small factor.
