### ISSUE TITLE
Allow for varying particle numbers in Simulation Archive. 

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#295]

**Comment by hannorein** [comment]
This is currently being implemented on the `binary_diff` branch and should be in a useable state by now. To try it out set the `simulationarchive_version` field in the simulation structure to `2`.

**Comment by hannorein** [comment]
So I think this should be fully working now. I did a few test runs myself and can't find any obvious issues. 

I think this should be the default type of SimulationArchive in the future as it "always works". The previous version is faster and produces smaller file sizes, but might not work in all cases. In general, we tend to turn on "safe modes" for all integrators, so I would suggest to do the same here. 

Would love to get some feedback before pushing it into the main branch. cc @dtamayo

**Comment by dtamayo** [comment]
This is amazing. One nice feature would be a python function that allows you to append a snapshot manually. That way you could for example add a final snapshot in a simulation that you want to stop when a particular condition is met through exceptions (e.g. collisions).

Looking at the C code, would it make sense to move the simulationarchive_time and simulationarchive_walltime updates into the reb_simulationarchive_append function so that we can simply call that single function from python? I'm happy to do it and update the ipython_example if you agree. Here's the relevant part of the source code:

https://github.com/hannorein/rebound/blob/binary_diff/src/simulationarchive.c#L452

**Comment by hannorein** [comment]
I agree. There seem to be three distinct use cases:
- Append a snapshot automatically, based on simulation time
- Append a snapshot automatically, based on wall time
- Append a snapshot manually
I think it would make sense to assume the worst case scenario, i.e. the snapshots are taken at random times. This would allow the same algorithm to be used when searching for a snapshot. I'll run some tests to see how much slower that would be.

**Comment by dtamayo** [comment]
It seems potentially confusing in the latest version that _set_filename is hidden in the automate_interval and automate_walltime functions, specifically in the case where you just want to add snapshots manually where you'd have to find that hidden function or do things differently and set simulationarchive_filename yourself. What if when you wanted to write you always had to call an init_simulationarchive(filename) function for consistency? 

I would personally also vote for removing automate_interval (just use snapshot manually) so there are fewer options in the documentation to understand, but don't have a strong opinion. Like you mentioned it would be nice if we didn't have either option, but I guess automate_walltime is harder to do yourself (from Python especially, since you don't want to set a python heartbeat...)

**Comment by hannorein** [comment]
It seems hard to do everything that the automate_interval function does by hand. I'm still playing around with ideas. Not sure which way to go. So your input is very much appreciated! But adding snapshots manually is easy:

    reb_simulationarchive_snapshot(r,"file.bin");

Not sure one can make that any easier!

**Comment by dtamayo** [comment]
Oops! I see now. I thought that it was set through simulationarchive_filename and didn't realize it was explicit. OK, I'm sure you're right. Writing every interval should be a common enough use case that I'm sure people will be happy to see a function that doesn't require them to think about it! Thanks.

**Comment by dtamayo** [comment]
I played around with the new syntax last night, and I actually really like it. I think you're right that you should always have to explicitly call reb_close_simulationarchive before appending, since otherwise your offsets become out of date, which might not be obvious to the user. And I think 'automate' really captures best what the functions are doing, so I think the names are great. 

I would kind of lean toward raising an error (rather than a warning) when you try to append to an existing simulationarchive from the middle. I can't think of a use case that isn't covered by writing to a separate file, and it can lead to a lot of surprises if you miss the warning and the bisection is giving you weird results after the fact. It also obviates the need to deal with additional logic...for example if I run

```
import rebound
sim = rebound.Simulation()
sim.add(m=1.)
sim.add(m=1e-3, a=1.)
sim.integrator="whfast"
sim.dt = sim.particles[1].P/20.
sim.automateSimulationArchive("satest.bin", interval=1.e3, deletefile=True)
sim.integrate(1.01e4)
sa = rebound.SimulationArchive("satest.bin")
sim = sa[-8]
sim.automateSimulationArchive(filename="satest.bin", interval=1.e3)
sim.integrate(2.e4)
sa = rebound.SimulationArchive("satest.bin")
for sim in sa:
    print(sim.t)

```

I restart where I expect, but hen get 4 snapshots right after one another (only posting the relevant times from the full list):

10000.03135758807 # final time in first block
3000.2920093484227 # first appended snapshot starting from middle
3000.60601165186
3000.9200139552977
3001.234016258735
4000.075343493483 # after this snapshots are every 1000 years

I think a reb_error that says that you can't append from the middle, and tells you to instead use a new filename avoids confusion for users and removes additional logic to deal with cases like the above.

**Comment by hannorein** [comment]
The usecase I had in mind is restarting a simulation.

**Comment by dtamayo** [comment]
Sorry, I meant the use case for writing to a simulationarchive when restarting from the MIDDLE of the simulationarchive (so that snapshots would be appended to the end). It seems to me like it would be better to raise an error and tell the user to write to a new filename

**Comment by hannorein** [comment]
Oh. Sorry. But how can one differentiate if the user is restarting from the middle or from the end?

**Comment by dtamayo** [comment]
You're right. It probably doesn't make sense to add more logic/flags. So it seems the case above saves several snapshots before restarting because the automateSimulationArchive function in python sets simulationarchive_next to 0, so for the first four time steps it increases by 1000 until simulationarchive_next is greater than the current time. I'm not sure why that logic is in there, but if I remove it the simulationarchive tests still pass.

**Comment by dtamayo** [comment]
One thing I came across is that since now snapshots are written at the exact final endpoint (it's possible I did that!) any time you do sim.integrate(time) (without exact_finish_time=0), then if you want to match any intermediate snapshots you have to integrate with exact_finish_time=0, but to match any endpoint time snapshots you have to do exact_finish_time=1. Would it make sense for the behavior to be that the auto interval will only save at integrator snapshots, and if you want to save at exact times, then you can simply save manually after a sim.integrate(time)? Simple example:

```
import rebound
sim = rebound.Simulation()
sim.add(m=1.)
sim.add(m=1e-3, a=1.)
sim.automateSimulationArchive("test.bin",interval=1e3,deletefile=True)
sim.integrate(1.e4)

sa = rebound.SimulationArchive("test.bin")
for i in range(1,sa.nblobs):
    sim = sa[i]
    x = sim.particles[1].x
    sim = sa[i-1]
    sim.integrate(sa[i].t, exact_finish_time=0)
    print(i, x == sim.particles[1].x)
```

prints true for all but last snapshot. There would obviously more of these edge cases if there were more sim.integrate calls.

**Comment by hannorein** [comment]
This happens because in the example above you integrate exactly up to a multiple of the interval in the first integration. If you change it to 
 
    sim.integrate(1.01e4)

It gives you the result you expect. So I think the case above is a specific floating point rounding issue which should not be a concern. I'd say overall this is the expected behaviour.

**Comment by hannorein** [comment]
I think this is all working now, so I'll close the issue.
