### ISSUE TITLE
Simulation returns all NaNs for particles, but doesn't fail

### ISSUE THREAD

**Issue by semaphoreP** [hannorein/rebound#303]
I've been trying to run some simulations backwards in time with four planets looking to test stability, and was finding simulations where all the particle positions and velocities (x,y,z,vx,vy,vz) ended up being NaN. The simulations would run to completion and without `rebound.Encouter` or `rebound.Escape` exceptions being raised. I mentioned this to @dtamayo and he suggested I post the issue here. I'm putting a python script that reproduces this error below. It requires [debug_orbit.zip](https://github.com/hannorein/rebound/files/1423386/debug_orbit.zip), which contains a fits file with orbital parameters (since github won't let me upload fits files). 

```
import numpy as np
import astropy.io.fits as fits
import rebound

sim = rebound.Simulation()
sim.G = 4.*np.pi**2 # units of Solar masses, au, years

with fits.open("debug_orbit.fits") as hdulist:
    this_config = hdulist[0].data
               
b_params = this_config[0]
c_params = this_config[1]
d_params = this_config[2]
e_params = this_config[3]

# add star
sim.add(m=b_params[-2])

# add planets
mjup = 0.0009543 # solar masses

# b
sim.add(m=6 * mjup, a=b_params[0], e=b_params[5], M=b_params[-1], omega=b_params[2], Omega=b_params[3]+np.pi/2, inc=b_params[4])
# c
sim.add(m=9 * mjup, a=c_params[0], e=c_params[5], M=c_params[-1], omega=c_params[2], Omega=c_params[3]+np.pi/2, inc=c_params[4])
# d
sim.add(m=9 * mjup, a=d_params[0], e=d_params[5], M=d_params[-1], omega=d_params[2], Omega=d_params[3]+np.pi/2, inc=d_params[4])
# e
sim.add(m=9 * mjup, a=e_params[0], e=e_params[5], M=e_params[-1], omega=e_params[2], Omega=e_params[3]+np.pi/2, inc=e_params[4])

sim.move_to_com()

# set up integrator, time step, and boudns
ps = sim.particles
sim.integrator = "whfast"
sim.dt = -ps[-1].P/100 # 1% of orbital period of shortest period planet, backwards in time

# stop simulation if planets get within mutual hill radius of inner two planets
RH = ps[-1].a*((ps[-1].m+ps[-2].m)/3/ps[0].m)**(1./3)
sim.exit_min_distance = RH
sim.exit_max_distance = 500. # au

try:
    sim.integrate(-10e6)
    print(sim.status())
except (rebound.Encounter, rebound.Escape) as e:
    print(e, sim.t)
```

**Comment by hannorein** [comment]
This is the same issue as #291. I've looked into this, but there is no easy way to get this working. Almost everything single line of code related to the simulation archive needs to be changed. I think this is not worth it as it makes it much harder to maintain the code. There is an easy and obvious workaround. Just switch the sign of the velocities and integrate forward. Then everything works as expected.

**Comment by dtamayo** [comment]
Hi Jason,

When I run this, I get an Encounter exception at t = -9651.08585383012. Is that not what you get? If so, do you have a set of conditions that gives NaNs? Nothing seems obviously wrong--it would help a lot to debug it if you can give us a problematic set of initial conditions. One quick thing to test might be to check whether you get NaNs when you integrate forwards in time. Qualitatively there's no sense in which integrating backwards is better than going forwards for answering the question of stability, since the chaos makes the problem time irreversible.

**Comment by semaphoreP** [comment]
Hi Dan, 
With the supplied fits file, I get all NaNs. For reference, I've tested this on two Ubuntu OSes, but not on other operating systems.

**Comment by semaphoreP** [comment]
I tested the same orbital parameters, but inverting their velocities and integrating forward in time, and the simulation seems to end in 9334.42 years with a particle escaping. So it seems to be a particular edge case...

**Comment by dtamayo** [comment]
Hm, the integrators are machine independent, so we should be able to reproduce your results with the same initial conditions. Would you mind loading the simulation on your computer,  then before integrating do

sim.save("test.bin")

And upload the binary? That should let me reproduce it. 

Also, you shouldn't get the same answer forwards and backwards for a single integration, but the same distribution of instability times for a suite of nearby initial conditions if you nudge them at the level of the machine precision. Just saying it doesn't matter which way you integrate for the overall exercise of seeing where things are stable, so it would remove the possibility of it being due to integrating backwards. As far as I'm aware that's only an issue with SimulationArchives, which you are not using. 

Anyway, I'm happy to take a look if you can upload a binary

**Comment by semaphoreP** [comment]
Thanks Dan! Here's a zip file with the binary inside: [debug.zip](https://github.com/hannorein/rebound/files/1423634/debug.zip). I confirmed that when I opened it up and ran the simulation -10 Myr that I got all NaNs for the particles positions and velocities.

**Comment by dtamayo** [comment]
Hey Jason, I can now reproduce everything. It looks like the innermost particle runs into the Sun in the timestep after -9297.2 and everything blows up. The issue is that your planets can farther in one of your adopted time steps than the size of the minimum hill sphere distance you want the simulation to stop at. You could decrease the timestep, or you could be happy with saying that if you get NaNs then your simulation is definitely unstable! It can be tricky with a fixed timestep integrator like a Wisdom Holman map that you don't know how eccentric your planets are going to get and how short a timestep you will need at late times in your simulation.

Also, you probably want to add your planets from the inside out rather than vice versa. You'll get smaller numerical errors with WHFast for these large masses, and if you ever look at the orbital elements you'll get smaller unphysical oscillations. There's a paper by Lee & Peale on using Jacobi elements for large planetary masses if you're interested in why this is. Hope that helps.

**Comment by semaphoreP** [comment]
Ah, that makes sense. I was guessing it was something like that. It'd be nice if there was some check of the state during the simulation to see if everything blew up, and to raise an exception if that happens. 

Anyways, I will check for NaNs in the output of my simulations. Thanks for the tip by the way of adding planets from the inside out!

**Comment by dtamayo** [comment]
No problem. We'll have to think about the best way to do that from C, but I agree that would be a nice feature.
