### ISSUE TITLE
Energy conservation in WHFast using openMP

### ISSUE THREAD

**Issue by dipto4** [hannorein/rebound#310]
Hello. I was running a simulation with WHFast as my integrator. I turned off the safe mode and was using an 11th order symplectic corrector with a timestep of 0.05 year. When I used openMP to run the simulation, I noticed that the relative energy error was about ~1e-6. I found it weird as the same simulation, when ran without openMP, gave a relative energy error of ~1e-13. Is this expected?
I don't know if this matters or not, but I was using Jacobi co-ordinates.

**Comment by hannorein** [comment]
Can you post a minimal working example that shows the problem?

Thanks!

**Comment by dipto4** [comment]
Sure! Here it is, along with the initial conditions file:
```
struct reb_simulation* const r = reb_create_simulation_from_binary("solar_system.in");
r->integrator   = REB_INTEGRATOR_WHFAST;
r->dt = 0.02;
r->ri_whfast.safe_mode = 0;
r->ri_whfast.corrector = 11;
r->G = 39.4769264214;
r->testparticle_type = 0;
float t = 0.0;
float t_final = 10000.0;
while (t < t_final) {
    reb_integrate(r,t);
}
```
I was using 8 threads with openMP.
[data.zip](https://github.com/hannorein/rebound/files/1468189/data.zip)

**Comment by dtamayo** [comment]
That doesn't look right. reb_integrate(r, t) tells the simulation to integrate up until time t. Are you missing a t += step in the while loop?

**Comment by dipto4** [comment]
@dtamayo Yes! Must've forgotten to put it in while typing it in on github. Sorry!

**Comment by hannorein** [comment]
I agree, there is a bug somewhere. I'm looking into it. 

Note that when you use WHFast with OpenMP you must use democratic heliocentric coordinates. This is because OpenMP only makes sense for large N and WHFast with large N only makes sense with democratic heliocentric coordinates. I also think that the symplectic correctors might be of little help if you have so many particles that warrant the use of OpenMP.
