### ISSUE TITLE
Adding planets in barycentric frame

### ISSUE THREAD

**Issue by pemanpardo** [hannorein/rebound#333]
I have an issue adding the planets in barycentric reference frame.
I have this code:

```
import rebound

sim = rebound.Simulation()
sim.add(m = 1)
sim.add(m = 1e-2, a = 1, e = 0)
sim.add(m = 1e-1, a = 2.0, e = 0)
sim.move_to_com()
orbits = sim.calculate_orbits(sim.calculate_com())
print orbits[0].a
print orbits[1].a
```

I should expect when I print orbits[0].a, orbits[1].a the values will be 1 and 2 respectively  since when I am adding the planets, I am adding them, respect to the barycentric frame and I gave as an input 1 and 2 as the value of semimajor axis. But I got different values for the semimajor axis.This is the answer of rebound:
0.588028130396
1.39032920788
 How can I add the planets respect to the barycentric frame?
For example if I do everything in Heliocentric, I've gotten the right answer so rebound print orbits[0].a = 1, print orbits[1].a = 2.0 with this code:

```
sim.add(m = 1)
sim.add(m = 1e-2, a = 1, e = 0)
sim.add(primary = sim.particles[0],m = 1e-2, a = 1, e = 0)
sim.add(primary = sim.particles[0],m = 1e-3, a = 2.0, e = 0)
orbits = sim.calculate_orbits(primary = sim.particles[0])
print orbits[0].a
print orbits[1].a
```

Thanks in advance for the help.

**Comment by dtamayo** [comment]
The sim.add routine cannot automatically add particles relative to the barycentric frame, because it doesn't know at the time it is adding what additional particles you are going to add in the future that will move the barycenter. What it does by default is add them relative to the center of mass of all the interior particles, i.e. using jacobi coordinates. You'd have to calculate the center of mass of all the objects first, and then add them using that primary. If you're really looking to do something as simple as the above with circular orbits all starting in a line, you could easily calculate the x and vy values by hand and add them that way

sim.add(m=1, x=x0, vy=vy0)

It's not totally clear to me that this is totally physical though...barycentric orbital elements would for example mean that for the middle body, the mean motion you would calculate would involve the total mass of the system including the planet further out...
