### ISSUE TITLE
removing particles

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#359]
Hi, 
I'm trying to remove from my simulation those particles which escape from the system, i.e., they are far away or when their orbit change to hyperbolic (`a<0`), when we can consider that they are ejected as well. I know that there is an exception that can be used for escape particles, however, I would like to consider both. I try something like that: 

```
for i, timex in enumerate(times):
    #print sim.t
    try:
        sim.integrate(timex)
        totalN[i] = sim.N_active
        print sim.N_active
        for j in range(1,sim.N_active):
            e[i][j] = ps[j].calculate_orbit(primary=sim.particles[0]).e
            a[i][j] = ps[j].calculate_orbit(primary=sim.particles[0]).a
            inc[i][j] = ps[j].calculate_orbit(primary=sim.particles[0]).inc    
            m[i][j] = ps[j].m
            w_cont[i][j] = ps[j].params["w_c"]
        if a[i][j] < 0. or a[i][j] > 50.:
            print "Particle ejected", j, a[i][j], e[i][j]
            sim.remove(index=j)
            print sim.N_active
```

Unfortunately, the part of the code to catch when a particle is ejected based in my condition: 
```
if a[i][j] < 0. or a[i][j] > 50.:
            print "Particle ejected", j, a[i][j], e[i][j]
            sim.remove(index=j)
            print sim.N_active
```
seems to be bad placed because any particle is removed. I don't know where can I place that or, better, if there is any way to use exception in rebound to address this problem..

Any suggestions? 
thanks in advance!

**Comment by dtamayo** [comment]
I didn't totally understand what you said at the bottom, but one thing that can trip you up is that when you remove a particle, the remaining particles in the index have to get shifted, so for example if you wanted to remove every particle from index 2 upwards, you would repeatedly remove particles[2]. To robustly keep track of particles when particles are continually being added or removed we implemented unique hashes that can avoid these kinds of issues altogether. See here:

https://github.com/hannorein/rebound/blob/master/ipython_examples/UniquelyIdentifyingParticlesWithHashes.ipynb

Also feel free to correct me if I missed what the real problem was!

**Comment by MilevaE** [comment]
Hi Dani, 

what I mean in the botton is: my routine to detect ejected particles is not working, I suspect because is in incorrect place inside the loop. So, the simulation runs well, some particles satisfy the condition to be consider as ejected (if a[i][j] < 0. or a[i][j] > 50.), but my routine is not detecting them. 

Sorry for the messy explanation and thanks a lot for your useful help :)

**Comment by dtamayo** [comment]
Oh! If I'm reading your code right, it seems like you're not looping over j when checking for escape, so aren't you only checking the last particle each time? One limitation of checking after calls to sim.integrate(time) is that you won't catch events that happen between your list of times, but I guess for ejections it shouldn't matter much.
