### ISSUE TITLE
Simulation Comparison Bug

### ISSUE THREAD

**Issue by zyrxvo** [hannorein/rebound#366]
When comparing two simulation with the subtraction operator, the newly created simulation object will change, and so will the simulations being compared. I've uploaded a Jupyter notebook gist that shows the error (https://gist.github.com/2e14706687d627cc7981a39a17c2a81d).

**Comment by hannorein** [comment]
Thanks. Right now these operators do not make a copy but modify the original operand. This is faster, but maybe not the intuitive behaviour one might expect. It's probably better to change that so that it returns a copy. That would make it work similar to how numpy arrays work. 

As a quick fix, you can make a copy of the simulation before adding/subtracting it.

**Comment by zyrxvo** [comment]
Thank you. That does make sense. I guess that wasn't clear to me, and I didn't notice the pattern.
