### ISSUE TITLE
Default Compilation Flags

### ISSUE THREAD

**Issue by jrob93** [hannorein/rebound#368]
Hi,

I was wanting to open an issue about the default rebound compiler flags. This might not be an issue but rather me not understanding exactly how rebound is compiled!

The behaviour I noticed is that the rebound code I am using gives different results when compiled and run on two different compute node systems. I'm doing a planetary migration simulation, and what appears to be happening is there is a slight differences in the integration that translates into big differences due to the chaotic nature of the system.

In your opinion would this be expected behaviour? The simulation results (using the exact same parameters) are consistent when done on the same compute node, however when I compare the set done on node 1 with the set done on node 2 they are not quite the same.

I am wondering if it has something to do with differences in processor, the linux distribution and/or compiler version?

In particular, in the rebound Makefile.defs it appears the default optimisation flag is -O3. This is where my knowledge is limited, but does -O3 mean optimisation at the expense of stringent precision? Or could optimisation be implemented slightly differently on different systems, leading to slight differences in arithmetic operations (which would blow up in my migration simulations)?

Cheers,
James

P.S. Here's the details (that I can remember) of the nodes we were using:

node1:
Intel(R) Xeon(R) CPU E5530
Fedora
gcc version 4.8.5

node2:
Intel i5
CentOS
A more recent version of gcc

**Comment by hannorein** [comment]
The actual integration algorithms should all be machine independent. But the way you setup your system might not. Specifically, REBOUND uses trigonometric functions like sin and cos to calculate the cartesian coordinates of particles from user provided orbital parameters. Could that be the case for you? If so, you can check that by setting up the system on one of your nodes, then saving it as a binary file, and restarting it on the other node. Both should give the same result. If not, then there is a bug in the integrator itself that makes it machine dependent. 

Making the orbit routines in REBOUND machine independent it something to think about. Basically, we'd have to ship REBOUND with its own implementation of all trigonometric functions. I'm a bit hesitant because it would be a lot of work to ensure these routines work in all edge cases and that they remain reasonably fast on mast architectures. It would be nice if these functions were defined somewhere in the C99 or IEEE standard.

**Comment by hannorein** [comment]
Hi James, any idea if this issue you describe could be related to generating the initial conditions?

**Comment by jrob93** [comment]
Hi Hanno,

Sorry for the late reply.

I think you are correct, we use the rebound orbit functions to calculate the planet's initial coordinates from an orbit. Then when I was looking through our code again I discovered another problem. 

We are doing a forced migration of the planets using an additional forces routine, and in this routine we use trig functions. Therefore the integration in our code cannot be expected to be machine independent.

So it looks like this is a problem with our implementation, not a rebound bug itself.

Thanks for the valuable insight!
James

**Comment by hannorein** [comment]
That makes sense! I'll close the issue then.
