### ISSUE TITLE
Output discarded test particles

### ISSUE THREAD

**Issue by MigoMueller** [hannorein/rebound#374]
We're studying impacts of (exo-) asteroids on (exo-)planets using Rebound /  MERCURIUS.  One feature we're missing is some way to output the IDs of discarded test particles and the reason why they were discarded for later analysis.  Swift/RMVS does offer this capability ('discard.out').

I suspect that would be easy to accomplish, and that the relevant functions / code pieces would have 

REB_COLLISION_DIRECT / 
REB_COLLISION_LINE  / 
REB_COLLISION_TREE / 
REB_COLLISION_SWEPP

in their name.  Is that correct?

I'll fork the code and have a go at it.  Any feedback is appreciated!

**Comment by dtamayo** [comment]
Hi Migo, the 'philosophy' behind REBOUND is, rather than hard-code in a particular behavior that might not work for someone down the road, to give you a flexible API that lets you do what you want. If you look at the CloseEncounters and EscapingParticles ipython examples, it will show you how to catch the exceptions raised when particles are removed, and in that except block you could write out your own customized discard.out or do whatever you'd like.

**Comment by hannorein** [comment]
I think the examples Dan pointed out should show you exactly what you're trying to do. I'll close this issue now, but feel free to open it again if you run into problems!

**Comment by MigoMueller** [comment]
Excellent feedback, thanks a lot!
