### ISSUE TITLE
Allowing argument and keyword argument unpacking operations for Particles.

### ISSUE THREAD

**Issue by DinoBektesevic** [hannorein/rebound#376]
I looked through the issues but found none similar. 

# Motivation

Recently I had a project where we used Rebound and its python wrappers. Considering this was a learning experience we used Jupyter Notebooks a lot. I was slightly annoyed by the fact that the expected interaction between `Particle` and `Simulation` object was quite verbose:

```
sim = rebound.Simulation()

p1 = rbd.Particle(sim, m=2., e=0.2, a=3., inc=4., omega=5.,  M=6.)
p2 = rbd.Particle(sim, m=3., e=0.2, a=3., inc=4., omega=5.,  M=6.)
...
particles = [p1, p2, ...]

sim.add(m=1)
for p in particles:
    sim.add(m=p.m, a=p.a, e=p.e, inc=p.inc, omega=p.omega, M=p.M)
```

Perhaps I missed something somewhere in the manual that makes this easier but retains the OOP aspects of it. Maybe I'm missing some nuances on how different arguments create different simulations. I don't know.

In any case, I found it tedious to have that long string of parameters in the `sim.add` line for every simulation created. I wrote a short wrapper class that allowed for shorter and more python-like unpacking operations:

```
for p in particles:
    sim.add(**p)
```

It was suggested to me that others might like this feature as well and tat I should open an issue. I have forked the repo (the 100th, congrats!) and implemented a short example demo in the `unpackingOps` branch mainly to test the waters and see if people are interested before I invest more effort into it. I could have just missed that part in the manual after all. 

# Changes

Unpacking is not really an operator as much as syntactic sugar. Argument unpacking operation invokes the `__iter__` method of an object and keyword argument unpacking operation iterates over object's keys and calls `__getitem__` on them. Essentially any object with `keys()` and `[ ]` operator can be unpacked. In our case the keys we want our object to have are all the valid orbital parameters that can go into `Simulation` and upon getting them we want to get the corresponding attribute of the class (`__getattr__`). That makes it possible to hotwire `[ ]` to act as `.`. Essentially all the changes boil down to adding 3 new methods, 2 of which are 1 liners. Currently the code in my fork manually defines what the keys that should be returned are, since I want to find out if this is an interesting feature or not.

# Issues

There are several issues that come to mind. First, I don't believe 'hackish' nature of the solution detracts or deviates from good programming practices as doing `Particle[ ]` is senseless and nobody will likely ever notice it can be done (and can be even further limited to only work for allowed keys). Second, `.keys()` needs to determine the correct orbital parameters to return, since its from them that the dictionary is constructed. Simulations with different parameters are not the same, i.e. adding only `a, e` is not the same as `a, e, omega` or `a, e, omega, M` etc. . Best option is to have `.keys()` return all validly set parameters, otherwise the behaviour is useless. If users want to manually under-specify their simulation they would have to write it all out manually. None of these issues are severe. 

The last one is weird however, I am not sure why, in the case when particle is initialized from orbital parameters, is the particle not added to the simulation automatically, or better to say the simulation isn't carried along with the particle? I am pretty inexperienced orbinaut, so I don't know for sure, but it seems to me that the only way that particle remains well defined, in this case, is with respect to a simulation. Weirdly many of the `orbi` list elements in `particle.py` are declared as properties too. So you are able to declare it at instantiation, but not access it again until particle is added to a `Simulation`? An example:
```
sim = rbd.Simulation()
sim.add(m=1)
p1 = rbd.Particle(sim, m=2., e=0.2, a=3., inc=4., omega=5.,  M=6.)
p1.omega
```
In any case currently I have hotwired this to work by creating a new attribute `self._refsim` that will carry a reference to the sim that was used to create the particle so that `calculate_orbit` can work, since I am returning several attributes that are actually properties in my `.keys()` method. 

Is this an interesting feature or no?

**Comment by hannorein** [comment]
Hi Dino!

Thanks a lot for opening this issue! I think you raise an interesting point, but it might be more complicated than one initially assumes. 

**OOP**
REBOUND is not an object oriented code. That's somewhat philosophical, but there are reasons. The goal was not to (re)allocate memory during a timestep. For long integrations, REBOUND might take 10^11 or 10^12 timesteps. That's a lot! If the memory structure changes even just once every timestep, it will lead to some fragmentation, which I was trying to avoid. Also, since the code supports OpenMP, I was trying to make sure there are not too many access conflicts and cache misses. Whether this all matters in real life, I'm not sure. I would have to write two versions of the code and then compare the runtime. But that was my thinking. 

**Orbits**
You already stumbled upon this. Particles without being part of a Simulation do not make much sense. For two reasons: first, you need to know the units, or G (which are defined in the Simulation). And second, orbital parameters don't make sense unless you also have a primary particle (and units). If I give you a random particle with x, y, z and vx, vy, vz coordinates, you won't be able to tell me a, e, etc. Since REBOUND is mostly about orbital dynamics, rather than, say an SPH code, we decided that particles really should always be part of a simulation. 

I agree that the piece of code you wrote is not very nice. I would write it as:

```
sim = rebound.Simulation()
sim.add(m=2., e=0.2, a=3., inc=4., omega=5.,  M=6.)
sim.add(m=3., e=0.2, a=3., inc=4., omega=5.,  M=6.)
```

This might not be the most OOP or pythonic way of doing it, but I think it makes sense.

**Unpacking**
I'm not sure I understand what the advantage of your unpacking solution is. If you really want to setup a particle before adding it to a simulation, you could do this:

```
sim = rebound.Simulation()
p = rebound.Particle(x=1,y=1,m=1,vx=1)
sim.add(p)
```

Let me know if this clears things up a bit.

Hanno

**Comment by DinoBektesevic** [comment]
> I'm not sure I understand what the advantage of your unpacking solution is. If you really want to setup a particle before adding it to a simulation, you could do this:

Aah, there it is. Looking through the manual all the examples were written as `sim.add(m=2., e=0.2, a=3., inc=4., omega=5.,  M=6.)` or `sim.add('SUN') and I guess it just never occurred to me to try and just add a `Particle` object. I suppose I should have just read the API manual (it says it right there!) or tried it but instead I just assumed it wouldn't work. 

Just to make it clear, the purpose was only really helping in 1 use-case - when REBOUND is used as a learning tool. In that scenario its more common to pick a system and then run multiple short simulations where some parameter is changed to see how they affect the orbits. In that case it gets a bit annoying and clutter-y, especially when there is more than a couple of particles in a system, to have to copy-paste the same block of `sim.add` text and its useful to have the ability to reuse objects. An example:

```
particles = [Particle(...), Particle(...), Particle(...), ....]

sim1 = Simulation()
for p in particles:
    sim1.add(p)

sim2 = Simulation()
for p in particles:
    sim2.add(p)
```

This problem is solved, now that I know its possible to just add them directly. Thanks!
