### ISSUE TITLE
Unintended extra output triggered by reb_output_check_phase

### ISSUE THREAD

**Issue by colinmcnally** [hannorein/rebound#384]
The intent of reb_output_check, which calls reb_output_check_phase seems to be to provide output at each step where the a multiple of the output interval falls between the current time minus the time step and the current time. However, this can do something slightly funny with the first time step, at least running IAS15. If t-dt < 0, then an extra output will get written.

The routine in output.c is:

```
int reb_output_check_phase(struct reb_simulation* r, double interval,double phase){
   double shift = r->t+interval*phase;
      if (floor(shift/interval)!=floor((shift-r->dt)/interval)){
        return 1;
      }
    // Output at beginning 
    if (r->t==0){
        return 1;
    }
    return 0;
}
```

where the usual call is with `phase=0`. At `r->t==0` the second if gets triggered, but then if the time step `r->dt` increases such that `r->t - r->dt < 0.0` the result is 

`floor(shift/interval) == 1.0`
`floor((shift-r->dt)/interval)) == 0.0`

and an output is triggered, even though r->t < interval. I'm not really sure what the intended general behaviour is however, as when `0 < phase < 1.0` you do probably want an output as soon as possible when `r->t > interval * phase` even if `r->t < interval`.

At the moment I've just added another check in my user-side code to catch the one odd seeming case of check_output, but maybe there's a simple patch that gives more predictable behaviour.

**Comment by hannorein** [comment]
HI Colin, 

Thanks for this report. I agree with your assessment. This is clearly not working as expected. Quick background: this function is ridiculously complicated. I wish it were easier. The reason it's so complicated is that there are many borderline cases that we've run into over the years. To list a few of the complications that might not be immediately obvious:

- Integrating a simulation backwards in time (negative dt)
- Integration can have a negative/positive time 
- Floating point issues, adding a very small number (dt) to a very large number (t)
- IAS15 has variable timesteps and can also rejecting steps completely (not advancing time at all)

I can't claim the function solves all of these issues, but you can imaging trying to change it having many unintended consequences. 

I think if you know precisely when you want to have outputs, you're better off just writing your own logic. It's much easier if you don't have to worry about all the border line cases which do not apply to your setup. For example, I often do something like (in pseudo code):

``
tmax = 10000
output_interval = 10
next_output = 0;
while sim.t<tmax:
   if sim.t>=next_output:
      output()
      next_output += output_interval
   sim.step()
``

As you can see, this would not work in general (e.g. it would not work when going backwards in time). It also requires additional storage (`next_output`). The original function does not need any storage (that was one of my original requirements because I wanted the simple helper function to be self-contained, otherwise you have to worry about allocating, resetting, releasing the variable -- and it becomes just even more complicated for such a simple task).

I'm not sure if that is a good enough answer to your query!

**Comment by colinmcnally** [comment]
Right, so the simple implementation of reb_output_check_phase is a feature, not a bug. The design intent is that one would go do something else when one runs into an edge case where it does not give the output needed.
