### ISSUE TITLE
Integrator to use

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#416]
Hello, I've been running some tests on some simulations using different integrators and I'm wondering, for cases such as simulations on orbital stability, should I use WHFast or the default IAS 15? I understand WHFast is not good for close encounters, but what if I don't know if the system will be dynamicall stable, which one is a better choice? I found that using different integrators will yield slightly different results.

Also, when using advanced features for WHFast such as extra speed and accuracy, how much a difference in the result would there be compared to running without extra speed and accuracy?

Thank you!

**Comment by hannorein** [comment]
If you just want to find out if something is stable or not, use WHFast. The simulation will no longer be accurate once a close encounter happens, but you already know that it's unstable by then. 

Keep in mind that the systems you're looking at are most likely chaotic. You should not expect to get the same result when using different integrators for any individual integration. But you should get the same statistical answer. Otherwise one of the integrators is not converged. 

You can get a speedup by setting safe_mode=0. There should be no downsides unless you're doing anything special such as adding non gravitational forces. If you think you need very high accuracy, you can turn on symplectic correctors. This certainly helps a lot for systems like the solar system where we know accurate initial conditions. For exoplanetary systems, the observational uncertainties are most likely so large that the correctors won't help much.

**Comment by zhexingli** [comment]
I see thank you. For the MEGNO simulation on unstable orbits, MEGNO plot return all red color on the grid as expected, but there're a few isolated grids that shows green or white. Should I just simply ignore them or they do mean something?

**Comment by hannorein** [comment]
You can look at each of them individually and see what's going on. Most likely a close encounter happened there and this makes the MEGNO value meaningless. Keep in mind that there are three possible regimes for a dynamic system: it can be non-chaotic (at least over "short" timescales), chaotic, or simply go unstable.

**Comment by zhexingli** [comment]
Got it. Thx
