### ISSUE TITLE
Questions about setting up accurate simulations for matching of JPL Ephermeris DE431mx

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound#420]
Hi Dr. Rien,
    I have reached out once before about other aspects of this codebase. I am still working on a publication that aims to use orbital integrations of a simulated meteoroid stream to determine the meteor flux at Earth over a range of years. I am getting to the final stretch of my work and am starting to narrow down on some sources of error for analysis. I began comparing the positions of some of my perturbing bodies (namely Earth and Jupiter) against their ephemerides and am noticing differences over time that I am unable to reduce any further.

I was wondering if you have any tips or suggestions for simulation work that aims to reproduce the motion of our solar system during a known range of time? 

I have a number of metrics covering these differences that I'd be happy to share but I'm not sure what you would find most informative without hearing your take on the matter.

Thank you again for this fantastic platform and I look forward to your reply,
    -Robert Melikyan
B.S. 2020 Ithaca College

**Comment by hannorein** [comment]
Hi Robert!

One thing you can (and should) always do is change the timestep. See if your results change. If so, then this is a warning flag that something is wrong. 

If you're working with test particles (I assume this is what you use for the meteor particles), you can also add a shadow particle. A shadow particle has exactly the same initial conditions than the original particles except that it is offset a tiny amount (say, 1e-10). If the system is deterministic, you should get the same results for both particles. But if the system is chaotic (which it probably is), then your tiny initial offset will become large over a finite amount of time. The shadow particle let's you estimate how quickly this offset grows (it gives you the Lyapunov time).

I hope this helps but feel free to poke me more!

Hanno

**Comment by Rmelikyan** [comment]
Hi Hanno!

Thanks for the quick reply!

I think that's a fantastic idea for the the particle production. And I am currently running my simulation (using mercurius) again with a refined timestep. At the moment I am particularly interested in what you would do if you were trying to reproduce the solar system during a given time range and wanted it to match a JPL solution within reasonable accuracy.

My particle production methods and non-gravitational forces all seem setup to run (Tamayo helped out there), and now I want to make sure that if my simulation says that the Earth sees a shower on March 30 2020, then our IRL Earth is in a position relatively close to what I simulated.

Thoughts?

Best,
    -Robert

**Comment by hannorein** [comment]
If you want to reproduce the JPL solution, go with IAS15 as the integrator. That should be reasonably fast for the timescales where a comparison to JPL makes sense. If the timescales are long, then you will have a hard time reproducing the JPL solutions because chaos amplifies any small differences (you can check that with the shadow particles). Also, any close encounter will be very sensitive to the initial conditions, and it's not obvious whether your solution or the JPL one is more accurate. Note that JPL does include some non-gravitational effects which can be important, especially for small objects such as asteroids and comets. You might also need to model some general relativistic precession. In short, it's getting complicated very quickly. Make sure there are no numerical issues (e.g. vary the timestep, etc). But then you probably need to think carefully about which physical effects are important. 

Hanno

**Comment by Rmelikyan** [comment]
Yes I see your point. I've already checked and seen that they use relativistic equations in their solutions. It certainly does all get quite complicated quickly! I appreciate your time and perspective. I'll keep working at it and will make sure to cite this awesome project once the paper makes its way out to the world.

Robert
