### ISSUE TITLE
How does measuring positions affect the simulation outcome?

### ISSUE THREAD

**Issue by rieder** [hannorein/rebound#431]
I am running some long-term (~Gyr) stability simulations of a three-body system with IAS15.
I find that if I measure the positions of the bodies more or less frequently, the outcome of the simulation is changed (i.e. one of the bodies is kicked out of the system or not).
Now I am wondering which result is more accurate: the one where I measure the positions more or less often? I would think that the result is caused by IAS15 discarding some internal values when measuring, making the less frequently measured simulation the more accurate one, but I would like to be more certain.

**Comment by dtamayo** [comment]
They're both equally accurate, it's just that the system is chaotic, so choosing to stop at different times along the way results in different (equally valid) outcomes. Perhaps a more satisfying approach would be to save SimulationArchives with some cadence, and then run the analysis after the fact. Then you have one reference trajectory (that's fixed), and you can get outputs at whatever intermediate times you want when doing the analysis.

If planets are undergoing close encounters throughout the integration you probably want to set a simulation archive storage interval in real CPU time rather than simulation time, so that when getting outputs at intermediate times after the fact, you can always get there very quickly (if you instead  output every e.g. 10^4 years of simulation time, and you have a couple deep encounters, it will take you a long time to go from the nearest snapshot to the time you want.

**Comment by rieder** [comment]
Thanks!
