### ISSUE TITLE
Adding hashes to particles obtained from NASA Horizons

### ISSUE THREAD

**Issue by ischurov** [hannorein/rebound#456]
I'm trying to create some objects from NASA Horizons and assign some hashes to them:

```
import rebound
sim = rebound.Simulation()
sim.add("Pluto", hash='pluto')
```

And get the following error:

```
TypeError: getParticle() got an unexpected keyword argument 'hash'
```

If I omit `hash` argument, particle is created with zero hash.

```
ps = sim.particles
ps[0].hash
# c_uint(0)
```

Are there any way to create objects from NASA Horizons with meaningful hashes?

**Comment by hannorein** [comment]
I've pushed a small change which allows you to use the above syntax. Alternatively, you could alway set it manually with 

    ps[0].hash = "pluto"

**Comment by ischurov** [comment]
Cool, thanks for prompt response and a fix! Great to see this library well-maintained!

I don't know why I didn't try to set `ps[0].hash` manually by myself, probably, there was misconception in my mind that it should be read-only after creation (like you cannot change key of an element in a dict), and/or I wasn't sure that numeric indexes are reliable (it seems thay are, before any simulations done that can affect them).  Anyway, `sim.add("Pluto", hash='pluto')` seem to be natural way to do it.

I tried to updated the documentation a little bit to address my misconceptions, see #457. I actually planned just to add a couple of lines but finally come with a bit of cleanup in "details" section. Hope this can be helpful to make the docs even better :)

**Comment by hannorein** [comment]
The "hash" idea is a bit of a compromise. We wanted to keep all the particles in one long array for efficiency, rather than using a linked list or objects. But on the other hand, we wanted a way to uniquely identifying the individual particles even after they move around in the array. This, together with it having to work in both C and Python leads to all kind of constraints. Again, thanks for your help.
