### ISSUE TITLE
Runtime Warning in Poincare Map example

### ISSUE THREAD

**Issue by Solardrop** [hannorein/rebound#462]
There is a runtime error that I am getting for the Poincare map example code. I am running it on a virtual box on windows that  has the latest version of python installed. I sudo installed rebound since it was giving me issues with the normal pip install, and the error I am getting is "you have to reset pointer functions after creating a reb_simulation struct with a binary file" I will admit that I am rather new to virtual machines, so I am a little lost at the moment. Any suggestions?

**Comment by hannorein** [comment]
Are you sure it's an error and not a warning?

**Comment by Solardrop** [comment]
Actually you are right, it is a runtime warning, not an error. That is an error on my part

**Comment by hannorein** [comment]
Then you can probably safely ignore it.

**Comment by Solardrop** [comment]
This might be me just being unfamiliar with virtual machines, But I am not given the option to ignore this runtime warning and the command line takes me back to the input line without executing anything, except for creating the resonant_system.bin file. Again sorry if this is something very obvious that I am misunderstanding.

**Comment by hannorein** [comment]
This message has nothing to do with virtual machines. 

It's just a warning that you need to reset function pointers if you've used them in the original REBOUND simulation for additional forces, heartbeat function, etc.

**Comment by Solardrop** [comment]
Ah I think the issue then is that I am getting this warning even though I have never used this module before. Do you have any recommendations for how to approach this? Also I misspoke earlier as well and am running python3.6

**Comment by hannorein** [comment]
I'm not sure what the problem is. I can only repeat myself, this message you mentioned is not an error message so the code should run regardless. You can ignore the warning. The example you're talking about is a jupyter notebook but you are taking about the command line. So I'm not sure what you're trying to do. I suspect you're having problems running the code in parallel for some reason. You can rewrite is without using the interruptible pool, just with the python map function.
