### ISSUE TITLE
Fourrier - LombScargle Analysis

### ISSUE THREAD

**Issue by gabiruzo** [hannorein/rebound#473]
Hello,

I am conducting some tests and verifying the resonance between bodies with non-Keplerian orbits, which prevents me from having precision of the resonance values ​​from the resonant angle for this. I am using the Fourrier analysis and the LombScargle periodogram, however I am not very sure regarding the normalization of my data, since I am using the standard REBOUND units, and I am not observing what I expected, in cases of 1/1 resonance the maximum peaks should be around the same value and in a similar way for the 1/2, 2/1 cases ......

I believe that there would be some difference in the normalization of the data (ws parameter) that is described in the example of the website with the ones that I am using ?

**Comment by hannorein** [comment]
Maybe it would help to try it out with a single eccentric keplerian orbit first? That should allow you to more easily understand the units.

**Comment by gabiruzo** [comment]
I did some tests and came to some conclusions.

![image](https://user-images.githubusercontent.com/53542579/103780036-3e044500-5013-11eb-95df-72469a4d520a.png)

![image](https://user-images.githubusercontent.com/53542579/103780049-43618f80-5013-11eb-88dd-6da7b4847095.png)


if I'm doing it right the ratio betweeen peaks is ~190periods / ~70periods ~=2.5 or 5/2 ressonance, so the units dosen't matter for this comparison.


For my cases:

![newplot](https://user-images.githubusercontent.com/53542579/103781967-b0762480-5015-11eb-835b-71520018b6a8.png)


![newplot (1)](https://user-images.githubusercontent.com/53542579/103781983-b3711500-5015-11eb-8ea5-21b93e708f71.png)

the first figure is a 1 / -1 resonance (retrograde orbit) due to the shape of the orbit that is observed for Keplerian orbits and the second must be 3 / -2 or 2 / -3. The spectral resolution I've used on this cases is 1 period and integration time 3e4*2*pi. 
I even tested the integration time up to 3e5 * 2 * pi, but the results vary and don't make much sense.

but for my cases I am not sure if this is working correctly. I think it may be the integration time or the spectral resolution, would you have any suggestions?

**Comment by hannorein** [comment]
I don't think this is a REBOUND issue so I'll close this for now. But here are a few pointers which might help you track down your problem:
- If the planets are interacting, then the frequencies will slowly change over time. That means non of this will ever be "exact". You need to find some way to estimate the precision you need, and a way to determine when you've reached that.
- It can be tricky to figure out which signal is real and which is due to your sampling/aliasing. Make sure you play around with the sampling frequency and sampling interval. Neither of these should affect your conclusion.
