### ISSUE TITLE
Divergence of Integration on Separate Computers

### ISSUE THREAD

**Issue by morganb-phys** [hannorein/rebound#50]
When I run the code below (a simple simulation of the Kepler-11 system) on two different computers, the output varies on the order of ~10^-9. 

![xdiff_comp](https://cloud.githubusercontent.com/assets/12415973/8481694/798a3990-20b2-11e5-80cc-6eab993ad631.png)

```python
import numpy as np
import rebound
from numpy import ndarray 
import matplotlib.pyplot as plt


model='MigaIVa'
integrator = 'ias15'

tmax = 1000. # Final time in years
Noutputs = 1001 # Number of outputs

rebound.integrator=integrator
rebound.G=4.*np.pi**2


K11 = rebound.Particle( m=0.950 )
rebound.add( K11 )
rebound.add( primary=K11, m=7.456e-6, a=0.091113, MEAN=3.122075,
             e=0.04423, omega=0.3604, inc=1.54 )  #K11b
rebound.add( primary=K11, m=1.070e-5, a=0.106505, MEAN=3.658224,
             e=0.01719, omega=0.9726, inc=1.55 )  #K11c
rebound.add( primary=K11, m=1.779e-5, a=0.154243, MEAN=0.711965,
             e=0.00633, omega=2.4566, inc=1.59 )  #K11d
rebound.add( primary=K11, m=3.426e-5, a=0.193940, MEAN=5.559193,
             e=0.00258, omega=4.1323, inc=1.55 )  #K11e
rebound.add( primary=K11, m=2.378e-5, a=0.249511, MEAN=1.598297,
             e=0.01073, omega=6.2107, inc=1.56 )  #K11f
rebound.add( primary=K11, m=7.952e-5, a=0.463991, MEAN=5.868932,
             e=0., inc=1.57, Omega=0. )  #K11g


rebound.move_to_com()

ps = rebound.particles
rebound.dt=0.01*np.sqrt(ps[1].calculate_orbit().a**3)

NumPlanet = rebound.N-1
        

print rebound.calculate_com()
            
x = np.zeros((NumPlanet,Noutputs))
times = np.linspace(0.,tmax,Noutputs)


for i,time in enumerate(times):

    rebound.integrate(time)
        
    for j in range(NumPlanet):
        x[j,i] = ps[j+1].x

Data = open('SimpleIntData.txt', 'a')
[Planet,Time] = np.ma.shape(x)
for t in range(Time):
    output = str(t)+' '
    for p in range(Planet):
        output = output+str(x[p,t])+' '
    Data.write(output+'\n')
Data.write('\n')
Data.close()
```

**Comment by dtamayo** [comment]
To eliminate possible culprits, you might try checking whether 4*np.pi**2 gives you the same number on the two machines, and whether rebound.dt and the planet elements are also the same.  It would make sense that the problem is in python and not in the C code (which Hanno has taken care to try and ensure that the output is machine independent).

**Comment by hannorein** [comment]
Thanks. I was able to reproduce that. Will try to figure out what is going on.

**Comment by hannorein** [comment]
Ok. I think I figured it out. This is due to two related issues. 

1. The first is due to slight differences in the initial conditions. If you compare the particles at t=0, you'll notice that there is already a difference on different machines. Because you have a chaotic system, these tiny (1 part in 1e16) differences get amplified during the simulations.

   The reason for the difference in the initial conditions comes from the python part. If you output a binary file, e.g. 

        rebound.save("test.bin")

   on one computer and then read it in on another

        rebound.load("test.bin")

  you'll get the same answer on both machines down to the last bit. 

  Why does python give you different answers on different machines? There are a couple of reason. First, to initialize the orbits, we use sine and cosine functions. These are not platform independent. There could also be a difference between different python versions. 

2. The second reason comes from the adaptive time stepping part of the `ias15` integrator. In there, we need to access the `pow` function from the math library. Again, this is not platform independent and will give slightly different answers depending on your compiler/operating system and/or CPU. If you turn off adaptive time stepping with 

        rebound.integrator_ias15_epsilon = 0.

  Then the results agree down to the last bit even for t>0.

**Comment by morganb-phys** [comment]
Thank you for looking into this so quickly! I also have it working now!
