### ISSUE TITLE
Strictly coplanar simulations

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#531]
Hi all,

Sorry in advance for what is probably going to be a naive question. I have a simulation that is strictly coplanar (Ltot = Lz). All objects will always lie in the same plane. I'm just wondering if REBOUND "knows" that it is a 2D simulation, and if there is an associated speedup, so that it doesn't bother tracking z, v_z of objects in the simulation.

Thanks!
Nick

**Comment by gabiruzo** [comment]
Hi Nick,

From my experience using REBOUND in coplanar problems I came to the conclusion that to ensure that the problem is fully coplanar you should first define the z, vz and 0 coordinates. I had serious difficulties both with REBOUND-IAS15 and with other integrators mainly in stability of some coplanar orbits due to the addition of the numerical error in these coordinates.

I hope this has helped you.

Gabriel.

**Comment by dtamayo** [comment]
No, REBOUND does not do separate planar calculations (the speedup would be
small anyway).

**Comment by hannorein** [comment]
- If a system is initially exactly coplanar, it will stay exactly coplanar forever. The numerical error in the z direction will not grow and always be exactly zero.
- And yes to what Dan said. There would only be a minimal speedup at best. Not worth thinking about!

**Comment by nchoksi4456** [comment]
Good to know. Thanks all!

**Comment by gabiruzo** [comment]
I was not very clear so correcting what I said above.

I had problems when I did not indicate exactly that the problem was coplanar.
