### ISSUE TITLE
Error calculating distance between particles

### ISSUE THREAD

**Issue by depra** [hannorein/rebound#557]
I am very new with solar system dynamics, so this might be a very silly question. 
I am trying to catch collisions with Jupiter. In the following example, I created a test particle with the same orbital elements as the planet. When I calculate the distance, I was expecting that it would be zero, but instead, it gives me a valor of  0.0050690505934084884.

Can somebody help me visualize what I am doing wrong here?

```
import rebound
init_date = 'JD2458600.5'

sim = rebound.Simulation()
sim.add('Sun', hash='Sun', date=init_date)
sim.add('Jupiter', hash='Jupiter', date=init_date)
sim.add(a = sim.particles[1].a, e=sim.particles[1].e, inc=sim.particles[1].inc,
        omega=sim.particles[1].omega, Omega = sim.particles[1].Omega,
        M=sim.particles[1].M, date=init_date)
sim.move_to_com()

dp = sim.particles[1] - sim.particles[-1]

distance = np.sqrt(dp.x*dp.x+dp.y*dp.y+dp.z*dp.z)
print(distance)
```

**Comment by dtamayo** [comment]
The reason is because by default, the sim.add function adds particles referenced to the center of mass of all previous particles in the simulation. So Jupiter has orbital elements defined with just the Sun in the system, but when you add the test particle, you're using orbital elements relative to a different center of mass that includes Jupiter. 

Try adding primary=sim.particles[0] (and remove date from the sim.add for the test particle since you're specifying all the orbital elements yourself). Should get a distance close to machine precision

**Comment by depra** [comment]
Thank you @dtamayo!
