### ISSUE TITLE
integrating simulation and extract ephemerides at a given JD

### ISSUE THREAD

**Issue by ifermion** [hannorein/rebound#564]
Hi all,

First of all, let me start off by thanking you all for such a amazing tool that rebound is, while I'm still discovering it.

Let's say you import the ephemerides from JPL using `sim.add()` and using the argument `date` to specify the Julian Date (JD) at which you want to instantiate the simulation (`sim.t = 0`). You keep integrating backwards (with something like `sim.dt = -0.001`) for let's say 100 years (preferably using 100*2pi, where 2pi is a year as I've seen in the examples). Then, say you have a list of specific JDs/ epochs that correspond to this period of 100 years, for which you want to extract ephermerides for certain objects in your simulation (like distance between two planets for example) as the integrations runs.

So I'm wondering how one would go about this task. Any ideas ?
There is a way to translate `sim.t` to JD ?

Please let me know if something is not clear, I'll try to explain better.

Thanks in advance !

**Comment by hannorein** [comment]
Hi, 

Sorry for the slow response. 

It's pretty straightforward. All you need to know is that one Julian year is defined as 365.25 days and that one REBOUND time unit is by default equal to one year/(2*pi) ... (because G=1 in code units). 

Say you import the ephemeris at some Julian day JD_0 and set the simulation time (sim.t) to 0 at the beginning. Then, you can integrate for some time T in REBOUND. In Julian days, that will correspond to JD_0 + T/(2.*pi)*365.25. That'll be accurate to about 1e-5 after 1 year. If you want it more accurate you need to take into account the difference between a Julian year and an actual year. 

(Robert posted some helpful snippets if you want the Julian date in days, months, years rather than the standard decimal format)

I hope that helps.

Hanno

**Comment by danielk333** [comment]
For precise time keeping and converting between different times I usually use [astropy.time](http://stsdas.stsci.edu/nadia/docs/_build/html/time/index.html). Especially since its allows seamless conversion between TAI (International Atomic Time) and UTC which is often used by instruments (radars ect) and TDB (Barycentric Dynamical Time) used by JPL Kernels and a few other sources.

**Comment by ifermion** [comment]
Hi @Rmelikyan, @hannorein, @danielk333 

Thank you very much for your replies. After some testing, I think the approch of using the python datetime object and swtiching to SI units described by @Rmelikyan  appears the most straighforward to me. I'm also using astropy.time Time objects to swiftly convert between UTC and JD.

Best regards !
