### ISSUE TITLE
Rebound installation error

### ISSUE THREAD

**Issue by ia-chow** [hannorein/rebound#572]

**Comment by ia-chow** [comment]
Hi,

I've tried to install REBOUND using pip (on Windows), but I'm getting a long error message that I can't parse. Any help would be appreciated. Thanks.

![error 2](https://user-images.githubusercontent.com/55640647/134708328-eb383d31-edc3-4756-b365-2c4a59bc5bfc.PNG)
![error](https://user-images.githubusercontent.com/55640647/134708330-085aed7e-21e0-4349-82bf-f90af6b498bb.PNG)

**Comment by Findus23** [comment]
Just as a general tip: Please always post error messages as text instead of images. This way other people with the same message will find this issue, it is easier to read for everyone and more accessible.

During the pip install the rebound C code gets compiled and rebound passes the `-Wno-unknown-pragmas` argument to the compiler here, which your C compiler doesn't seem to understand ("invalid numeric argument"):

https://github.com/hannorein/rebound/blob/2a993cf13fb6ff285b81c95207bb820a17cdfb72/setup.py#L57

So (as I think rebound isn't "officially supported" on Windows) you can either adapt the installation setup to work with your compiler setup or use Rebound inside WSL as recommended here: https://rebound.readthedocs.io/en/latest/quickstart_installation/

**Comment by hannorein** [comment]
Hi Ian, 

I'm not very familiar with Windows myself but REBOND seems to work for most people using the "linux subsystem for windows". Are you using that?

If so, and the error still occurs, you could try to run setup.py directly (clone the repo), and remove the no-unkown-pragma statement that appears on line 57. 

Hanno

**Comment by hannorein** [comment]
Hi Ian, from your e-mail I figure you have solved the problem. So I'll close the thread here. If you can, maybe post the solution here so that others can find it if they have the same issue.

**Comment by ia-chow** [comment]
Thanks for the help in your previous comment; using REBOUND inside of WSL fixed the issue for me.
