### ISSUE TITLE
Parallel processing in HPC cluster

### ISSUE THREAD

**Issue by ssah1378** [hannorein/rebound#595]
Hi, 

I have been trying to run an N-body simulation with REBOUND on the HPC3 cluster of my university, but for some reason it cannot utilize parallel core processing. It takes twice as much time, compared to my own MacBook, since it is only using one core. The most recent package that I used on HPC3 was Galpy, and that adapted itself accordingly and utilized the 80-cores on HPC3 that I set for it to use. Do you have any suggestions about what should I do? Please let me know if it would help to upload my code. 

Cheers, 
Shasha

**Comment by hannorein** [comment]
You need to provide a bit more information. What kind simulations are you running? How many particles? What particle type? What integrator, collision modules, etc are you using?

**Comment by ssah1378** [comment]
I am defining Sun, Jupiter, Earth, 1000 comets (for Oort Cloud), and a star passing by, using the default integrator with dt=1000 thousand years over a period of 5Myr. Here is my code:

#creating values for eccentricity
eccentricities = []
for i in range(0,1000):
    eccentricities.extend(repeat(i/1000, 2*(1000-i)-1)) 

#creating values for the semi-major axis
semimajor = []
for i in range(0,1000):
    semimajor.extend(repeat((10**4 + i*10**2), int(9*10**11/((10**4 + i*10**2)**2)-0.15)+178))
    
#creating a list for both eccentricity and semimajor, randomly assigning them to eachother
eanda = []
for i in range(0,1000000):
    eanda.append([semimajor[random.randint(0,999999)], eccentricities[random.randint(0,999999)]])
    

sim = rebound.Simulation()

sim.units = ('yr','AU','Msun')
sim.dt = 1000

sim.add(m=1)

sim.add(m=1e-3, a=5.2, e=0.05)

p = rebound.Particle()
p.m = 1
p.x = 20000
p.vy = 6
sim.add(p)

comets_init = []
count = 0
while count < 100: #100000
    count += 1
    sim.add(m=2e-18, 
            a=float(eanda[count-1][0]), #N_a = Constant*(1 - a_inner / a)
            e=float(eanda[count-1][1]), #F_e = 1 - e^2
            inc=float(random.uniform(-np.pi/2, np.pi/2)), #isotropy
            Omega=float(random.uniform(0,np.pi))) #isotropy
    comets_init.append([sim.particles[count+2].a,
                       sim.particles[count+2].e,
                       sim.particles[count+2].inc, 
                       sim.particles[count+2].Omega])

sim.integrate(5000)

sec_end = time.time()
print("Runtime =", sec_end - sec_beg)

comets_fin = []
for orbits in sim.calculate_orbits():
    comets_fin.append([orbits.a, orbits.e, orbits.inc, orbits.Omega])

Please let me know if you need any further information, 
Cheers, 
Shasha

**Comment by hannorein** [comment]
Hi Sasha. Thanks for the details. A couple of comments which might help you:

- You probably want your comets to be [test particles](https://rebound.readthedocs.io/en/latest/ipython_examples/Testparticles/), so set `N_active` to 3.
- The default integrator IAS15 is adaptive, so the timestep you set doesn't really matter aside from the initial one.
- The adaptive timestep will be dominated by the particle that is closes to the sun. Because it's a global timestep, it might be faster to run multiple simulations with fewer particles (say 10 particles each). That way the average timestep will be larger, and the timestep will only get small if one of the 10 particles is having a close encounter. Alternatively, you could explore some of the other integrators (mercurius, or TES). I can't give you any definite advice as to which one is best. It really depends on your specific setup. 
- 1000 particles is not all that many. You're not going to be able to gain much by parallelization. Especially if you use `N_active=3` and the problem is basically O(N) rather than O(N^2). Maybe a factor of 5 or 10 if you're lucky. But as long as the 1000 particles don't interact with each other, this doesn't really matter. You can just run multiple single core jobs with fewer particles, then combine the results later.

I hope that helps!

**Comment by ssah1378** [comment]
Thank you very much for all the notes. This is a test code; the actual number of particles that I would eventually need to run is about 10^6. So what do you suggest me to do for this number of comets? Run 10 different 100,000 comet simulations and then combine? 1000 comet system takes about 1hr on HPC cluster so I am expecting a few days for 100,000 comets. Thank you for all the explanations again. Please let me know if you have any further notes to share. 

Cheers, 
Shasha

**Comment by hannorein** [comment]
Unless there's some interaction between particles, there is no need to bother with parallelization. Just run a couple of single core jobs and combine the results later. 

But with that many particles, IAS15 is really not the integrator you want to use. An integrator like WHFast with a fixed timestep would perform best unless you care about close encounters. If close encounters matter, try out Mercurius. This will require some fine tuning of various parameters to get the best performance/accuracy.

**Comment by ssah1378** [comment]
Thank you very much.
