### ISSUE TITLE
Slightly inflated eccentricity values

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#597]
Hello,

I'm trying to simulate the Jupiter's moon system with the four Galilean moons and the four innermost small moons. But I found out the result of the simulation has slightly larger mean eccentricity values compared to those reported on the Horizon system (https://ssd.jpl.nasa.gov/sats/elem/). I then looked at the Jupiter simulation tutorial on the rebound website (https://rebound.readthedocs.io/en/latest/ipython_examples/Resonances_of_Jupiters_moons/) and it appears eccentricities are inflated a bit there as well (except Callisto):
Simulation mean eccentricities estimated from the plot shown in the tutorial:
Io: 0.006, Europa 0.012, Ganymede: 0.0025, Callisto: 0.007
compared to true e's: Io: 0.00472, Europa: 0.00981, Ganymede: 0.00146, Callisto: 0.00744

For my four simulation runs, I put four Galilean moons in the system and added alongside them one of the four inner most moons (Metis, Adrastea, Amalthea, Thebe) for each simulation and tested its orbital evolution. In all cases the mean eccentricities were much higher than reproted:

Metis: sim: 0.0362, true: 0.006
Adrastea: sim: 0.0344, true: 0.007
Amalthea: sim: 0.0357, true: 0.00613
Thebe: sim: 0.0856, true: 0.015

What could be the cause of the observed inflated eccentricity values in my simulations and the tutorial simulations? Could it be that tidal forces not included in these simulations where otherwise tidal circularization could have easily lowered the e's of these orbits to near circular?

My code is attached.
[Run_Moons.py.zip](https://github.com/hannorein/rebound/files/8628739/Run_Moons.py.zip)

**Comment by ssah1378** [comment]
This is the problem that I have been having with my simulations too!

**Comment by hannorein** [comment]
There is nothing wrong with your code. A few possible ideas as to why you're not getting the results you're expecting:

- You could include the Sun or Jupiter's J2 moment to be more precise. (I don't think those will have a big effect)
- Your initial conditions are slightly off. You could initialize everything from Horizons using `sim.add(["Jupiter","Io","Europa","Ganymede","Callisto"])`
- Where did you find the literature value for the average eccentricity? It should specify over what timescale those have been calculated. Since the eccentricities change over various different timescales, this is important.
- You could reduce the timestep a little. 20 timesteps per orbit should be fine, but since you're looking at pretty small eccentricities, maybe another factor of 5 smaller wouldn't hurt.


I hope this helps.

**Comment by zhexingli** [comment]
Thanks Hanno. Which ones of the initial conditions are off? I took those orbital parameters directly from JPL Horizon system, especially eccentricities with time from the start of the century till now. The mean values are from JPL Horizon system as well, though it doesn't say what timescales are for those mean elements.

Is there a python tutorial for including the J2 moment?

Could the non-inclusion of tidal forces be part of the reason?

**Comment by hannorein** [comment]
It can be tricky to use orbital parameters if you want to have very precise initial conditions because of various ambiguities. For example, when I query the initial eccentricity of Io right now, I get 0.00449, but you use 0.0041. Speaking from experiences, use cartesian coordinates to initialize solar system objects and you're much more likely to get it right. 

Check REBOUNDx [for a tutorial on J2](https://github.com/dtamayo/reboundx/blob/master/ipython_examples/J2.ipynb). 

I would guess the tidal forces are a higher order effect.

**Comment by zhexingli** [comment]
I see. Thank you. I've never initiated the run with cartesian coordiantes before. In this case, I just provide a mass, and put all the particles at x coordinate with their semi-major axis values, with y=0, z=0, and without any specifications on eccentricity or inclination?

**Comment by hannorein** [comment]
No. You can either let REBOUND do the work for you and just use `sim.add(["Jupiter","Io","Europa","Ganymede","Callisto"])`. or you go to NASA Horizons, and query the cartesian coordinates for the particles you're interested in. Then you add those with `sim.add(m=..., x=..., y=..., z=..., vx=..., vy=..., vz=...)`

**Comment by zhexingli** [comment]
Got it. Thank you so much! I'll close this for now.

**Comment by ericagol** [comment]
@hannorein   This is a great notebook!   I tried running the example notebook locally, and obtained completely different results compared to the one in the documentation (for example, the initial orbit plot in the local version of the notebook shows each moon starting at a different longitude than in the documentation example; the mean-motion & periods differ as well; and the dynamical results look completely different, especially the resonant angles, which circulate rather than librate).  I am wondering whether this is due to a different initial time being used.  At what time are the initial orbital elements taken from the NASA Horizons database?  Is there a way to change this initial time to match the one in the example?  Thanks in advance!  -Eric

**Comment by hannorein** [comment]
Hi Eric, 

I just reran this myself and I agree the values are different. I think you're right that this is due to different initial conditions. Given the notebook was last updated on Jan 6, 2021, you could try that date in the Nasa Horizon query (date="2021-01-06"). Lesson learned: we should really include the date in those queries so that the notebooks are reproducible...

Hanno

**Comment by ericagol** [comment]
Thanks for the quick response!
