### ISSUE TITLE
switching integrators after loading from SimulationArchive

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#598]
Hi all, 

I am running simulations with MERCURIUS. I want to load a snapshot from the SimulationArchive and switch the integration method to IAS15. But when I switch the integrator, things break (Python crashes, I don't even get an error).  Is this supposed to happen? I can also supply the simulation archive if needed.

```
sa = rebound.SimulationArchive("secular7_Np3_seed2")
sim = sa.getSimulation(1000)
sim.integrator = "ias15" # NC: commenting out this line avoids simulation crashing
sim.integrate(sim.t + 100)
```

Thanks!
Nick

**Comment by Findus23** [comment]
This sounds a bit like https://github.com/hannorein/rebound/issues/547

**Comment by nchoksi4456** [comment]
Thanks! Yes, it seems to be exactly the same issue.

**Comment by hannorein** [comment]
Thanks. So same question as in #546: Can you provide me with a short example that I can use to reproduce the error?

**Comment by Rmelikyan** [comment]
So, in the 20 minutes I played around with this, I wasn't able to reproduce the same exact error that I remember from last summer or that seems to be referred to here. But as a starting point, this notebook does demonstrate that there is some unintended consequences when switching from Mercurius to either IAS15 or WHFast. I tried some other permutations such as switching from IAS15 to Mercurius, and this does seem to be a one-way phenomenon.

[Copy and run this notebook to see for yourself](https://colab.research.google.com/drive/1j_k5Di2jZtKSxEdks-mnnmST1Wny7Vle?usp=sharing)

Something is wrong here... I'm just not precisely sure what. When preparing simulation binaries in python for use in a C-program, I've taken to opening the files, and manually copying the particle and simulation parameters into a new simulation object in order to avoid this region of the codebase.

I hope this information helps,
-Robert

**Comment by hannorein** [comment]
Thanks a lot! I'll look into it.

**Comment by hannorein** [comment]
Ok. That helped a lot. The issue is not in the SimulationArchive itself, but in the `getSimulation` routine. A quick workaround is to pass `keep_unsynchronized=0` as an argument. But this is clearly not the correct behaviour and I'll need to fix the logic.

**Comment by nchoksi4456** [comment]
Sorry for slow response on my end! Glad the bug was identified. Thanks Hanno.
