### ISSUE TITLE
Attribute error Question

### ISSUE THREAD

**Issue by LefterisDimitri** [hannorein/rebound#765]
Hello,

I was trying to run: a) Laplace-LagrangeSecularTheory.ipynb 

and
                                b) FrequencyAnalysis.ipynb from celmech 

and i saw these errors :

a) module 'rebound' has no attribute 'SimulationArchive'
b) 'Simulation' object has no attribute 'automateSimulationArchive'

I would appreciate some advice.

**Comment by hannorein** [comment]
The API has changed in REBOUND Version 4.0. `automateSimulationArchive` is now `save_to_file( filename, interval=None, walltime=None, step=None, delete_file=False)` and `SimulationArchive` is `Simulationarchive`. This needs to be updated in celmech (cc @shadden), not REBOUND, so I'm closing this issue here.

**Comment by LefterisDimitri** [comment]
Thank you for your help mr. Hanno Rein
